### ISSUE TITLE
error in model.preprocess_data if an annData object is given as input in model.get_data

### ISSUE THREAD

**Issue by rmathieu25** [jaydu1/VITAE#1]
Hello,

Thanks for developing VITAE.

I tried to use VITAE but I have an issue regarding the model.preprocess_data when I give an annData object as an input of model.get_data function.

The preprocession should be done by scanpy which it is installed but I get the error: 

```
# fit in data
model.get_data(adata=data,                   # count or expression matrix, (dense or sparse) numpy array 
               labels = data.obs['cluster_label'],       # (optional) labels, which will be converted to string
               gene_names = data.var['features'], # (optional) gene names, which will be converted to string
               cell_names = data.obs['sample_name']    # (optional) cell names, which will be converted to string
              )

# preprocess data
model.preprocess_data(gene_num = 2000,        # (optional) maximum number of influential genes to keep (the default is 2000)
                      data_type = 'UMI', # (optional) data_type can be 'UMI', 'non-UMI' or 'Gaussian' (the default is 'UMI')
                      npc = 64              # (optional) number of PCs to keep if data_type='Gaussian' (the default is 64)#)
                      )
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-aa66b286b1ac> in <module>()
     35 model.preprocess_data(gene_num = 2000,        # (optional) maximum number of influential genes to keep (the default is 2000)
     36                       data_type = 'UMI', # (optional) data_type can be 'UMI', 'non-UMI' or 'Gaussian' (the default is 'UMI')
---> 37                       npc = 64              # (optional) number of PCs to keep if data_type='Gaussian' (the default is 64)#)
     38                       )

2 frames
/usr/local/lib/python3.7/dist-packages/VITAE/preprocess.py in _recipe_seurat(adata, gene_num)
    238     This uses a particular preprocessing
    239     """
--> 240     cell_mask = sc.pp.filter_cells(adata, min_genes=200, inplace=False)[0]
    241     adata = adata[cell_mask,:]
    242     gene_mask = sc.pp.filter_genes(adata, min_cells=3, inplace=False)[0]

NameError: name 'sc' is not defined

```
I do not understand what is the issue because you import scanpy as sc in your defined function?

Thank you in advance.

Best regards.

**Comment by jaydu1** [comment]
Hi,

Thanks for reporting the issue. The problem has been fixed in the latest version v1.1.5. 

Another workaround is to first preprocess your data with `scanpy` on your own and then pass the preprocessed `anndata` object to VITAE functions. This allows you to have more flexibility to preprocess the data.

Best.

**Comment by rmathieu25** [comment]
Hello, 

Thank you for you answer.

How can I install the last version of VITAE? I cannot install with the git+[url] option because you have not a setup file, right? 

I tried to use the command line:
```
!pip install --upgrade --force-reinstall pyvitae

```
but still the version 1.1.4 is installed.

Actually, I tried to prepoccess the adata object beforehand but I am having the following issues:
```
# fit in data
model.get_data(adata=data,                   # count or expression matrix, (dense or sparse) numpy array 
               labels = data.obs['cluster_label'],       # (optional) labels, which will be converted to string
               gene_names = data.var['features'], # (optional) gene names, which will be converted to string
               cell_names = data.obs['sample_name']    # (optional) cell names, which will be converted to string
              )


# preprocess data
model.preprocess_data(gene_num = 2000,        # (optional) maximum number of influential genes to keep (the default is 2000)
                     data_type = 'Gaussian', # (optional) data_type can be 'UMI', 'non-UMI' or 'Gaussian' (the default is 'UMI')
                      npc = 64,                # (optional) number of PCs to keep if data_type='Gaussian' (the default is 64)
                     processed=True)


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/VITAE/lib/python3.9/site-packages/VITAE/preprocess.py in preprocess(adata, processed, dimred, x, c, label_names, raw_cell_names, raw_gene_names, K, gene_num, data_type, npc, random_state)
    166         try:
--> 167             label_names = adata.obs.cell_types
    168         except:

~/anaconda3/envs/VITAE/lib/python3.9/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5464                 return self[name]
-> 5465             return object.__getattribute__(self, name)
   5466 

AttributeError: 'DataFrame' object has no attribute 'cell_types'

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-12-d13f8a1785c1> in <module>
     34 
     35 # preprocess data
---> 36 model.preprocess_data(gene_num = 2000,        # (optional) maximum number of influential genes to keep (the default is 2000)
     37                      data_type = 'Gaussian', # (optional) data_type can be 'UMI', 'non-UMI' or 'Gaussian' (the default is 'UMI')
     38                       npc = 64,                # (optional) number of PCs to keep if data_type='Gaussian' (the default is 64)

~/anaconda3/envs/VITAE/lib/python3.9/site-packages/VITAE/VITAE.py in preprocess_data(self, processed, dimred, K, gene_num, data_type, npc)
    114         self.cell_names, self.gene_names, self.selected_gene_names, \
    115         self.scale_factor, self.labels, self.label_names, \
--> 116         self.le, self.gene_scalar = preprocess.preprocess(
    117             self.adata,
    118             processed,

~/anaconda3/envs/VITAE/lib/python3.9/site-packages/VITAE/preprocess.py in preprocess(adata, processed, dimred, x, c, label_names, raw_cell_names, raw_gene_names, K, gene_num, data_type, npc, random_state)
    168         except:
    169             if label_names is not None:
--> 170                 label_names = label_names[cell_mask]
    171 
    172         cell_names = adata.obs_names.values

UnboundLocalError: local variable 'cell_mask' referenced before assignment

```

Thank you in advance.

Best regards

**Comment by jaydu1** [comment]
Hi,

For installing the latest version via `pip`, please use the following command.

```
pip install --upgrade pyvitae
```

Note that the option `--force-reinstall` you use will reinstall the current version of the installed package.


Thanks for reporting the issue. I have fixed it in v1.1.6. If there are no other issues with the preprocessing function, I'll close this one. For other problems, feel free to open new issues. Thanks.

Best.

**Comment by rmathieu25** [comment]
Hello,

I have already tried this commmand line but still the 1.1.4 version is installed

```

!pip install --upgrade pyvitae 

Requirement already satisfied: pyvitae in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (1.1.4)
Collecting pyvitae
  Using cached pyvitae-1.1.6-py3-none-any.whl (35 kB)
Requirement already satisfied: matplotlib in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (3.4.2)
Requirement already satisfied: statsmodels in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.12.2)
Requirement already satisfied: jupyter in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (1.0.0)
Requirement already satisfied: networkx in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (2.5.1)
Collecting tensorflow-probability==0.11.*
  Using cached tensorflow_probability-0.11.1-py2.py3-none-any.whl (4.3 MB)
Requirement already satisfied: umap-learn>=0.5.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.5.1)
Requirement already satisfied: leidenalg in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.8.4)
Requirement already satisfied: scikit-misc in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.1.4)
Requirement already satisfied: numba in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.53.1)
Requirement already satisfied: pandas in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (1.2.4)
Requirement already satisfied: seaborn in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.11.1)
Collecting pyvitae
  Using cached pyvitae-1.1.5-py3-none-any.whl (35 kB)
Requirement already satisfied: tensorflow>=2.3.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (2.5.0)
Requirement already satisfied: scikit-learn in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.24.2)
Requirement already satisfied: tensorflow-probability>=0.11.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyvitae) (0.12.2)
Requirement already satisfied: wrapt~=1.12.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.12.1)
Requirement already satisfied: keras-preprocessing~=1.1.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.1.2)
Requirement already satisfied: gast==0.4.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (0.4.0)
Requirement already satisfied: numpy~=1.19.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.19.5)
Requirement already satisfied: six~=1.15.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.15.0)
Requirement already satisfied: typing-extensions~=3.7.4 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (3.7.4.3)
Requirement already satisfied: google-pasta~=0.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (0.2.0)
Requirement already satisfied: grpcio~=1.34.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.34.1)
Requirement already satisfied: absl-py~=0.10 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (0.12.0)
Requirement already satisfied: protobuf>=3.9.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (3.17.1)
Requirement already satisfied: h5py~=3.1.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (3.1.0)
Requirement already satisfied: flatbuffers~=1.12.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.12)
Requirement already satisfied: opt-einsum~=3.3.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (3.3.0)
Requirement already satisfied: tensorboard~=2.5 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (2.5.0)
Requirement already satisfied: astunparse~=1.6.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.6.3)
Requirement already satisfied: tensorflow-estimator<2.6.0,>=2.5.0rc0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (2.5.0)
Requirement already satisfied: keras-nightly~=2.5.0.dev in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (2.5.0.dev2021032900)
Requirement already satisfied: wheel~=0.35 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (0.36.2)
Requirement already satisfied: termcolor~=1.1.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (1.1.0)
Requirement already satisfied: markdown>=2.6.8 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (3.3.4)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (1.8.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (2.25.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (1.30.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (0.4.4)
Requirement already satisfied: setuptools>=41.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (57.0.0)
Requirement already satisfied: werkzeug>=0.11.15 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (2.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (4.2.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (1.26.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (2.10)
Requirement already satisfied: oauthlib>=3.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (3.1.0)
Requirement already satisfied: dm-tree in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow-probability>=0.11.0->pyvitae) (0.1.6)
Requirement already satisfied: cloudpickle>=1.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow-probability>=0.11.0->pyvitae) (1.6.0)
Requirement already satisfied: decorator in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow-probability>=0.11.0->pyvitae) (4.4.2)
Requirement already satisfied: pynndescent>=0.5 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from umap-learn>=0.5.0->pyvitae) (0.5.2)
Requirement already satisfied: scipy>=1.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from umap-learn>=0.5.0->pyvitae) (1.6.3)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from numba->pyvitae) (0.36.0)
Requirement already satisfied: joblib>=0.11 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pynndescent>=0.5->umap-learn>=0.5.0->pyvitae) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from scikit-learn->pyvitae) (2.1.0)
Requirement already satisfied: ipykernel in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (5.5.5)
Requirement already satisfied: nbconvert in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (6.0.7)
Requirement already satisfied: qtconsole in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (5.1.0)
Requirement already satisfied: jupyter-console in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (6.4.0)
Requirement already satisfied: notebook in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (6.4.0)
Requirement already satisfied: ipywidgets in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (7.6.3)
Requirement already satisfied: traitlets>=4.1.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (5.0.5)
Requirement already satisfied: tornado>=4.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (6.1)
Requirement already satisfied: ipython>=5.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (7.23.1)
Requirement already satisfied: jupyter-client in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (6.1.12)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (3.0.18)
Requirement already satisfied: pygments in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (2.9.0)
Requirement already satisfied: pexpect>4.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (4.8.0)
Requirement already satisfied: matplotlib-inline in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.1.2)
Requirement already satisfied: backcall in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.2.0)
Requirement already satisfied: pickleshare in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.7.5)
Requirement already satisfied: jedi>=0.16 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.18.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.8.2)
Requirement already satisfied: ptyprocess>=0.5 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.7.0)
Requirement already satisfied: wcwidth in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.2.5)
Requirement already satisfied: ipython-genutils in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from traitlets>=4.1.0->ipykernel->jupyter->pyvitae) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipywidgets->jupyter->pyvitae) (5.1.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipywidgets->jupyter->pyvitae) (3.5.1)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipywidgets->jupyter->pyvitae) (1.0.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (3.2.0)
Requirement already satisfied: jupyter-core in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (4.7.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (21.2.0)
Requirement already satisfied: Send2Trash>=1.5.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (1.5.0)
Requirement already satisfied: pyzmq>=17 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (22.1.0)
Requirement already satisfied: jinja2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (3.0.1)
Requirement already satisfied: prometheus-client in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (0.10.1)
Requirement already satisfied: argon2-cffi in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (20.1.0)
Requirement already satisfied: terminado>=0.8.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter-client->ipykernel->jupyter->pyvitae) (2.8.1)
Requirement already satisfied: cffi>=1.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from argon2-cffi->notebook->jupyter->pyvitae) (1.14.5)
Requirement already satisfied: pycparser in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter->pyvitae) (2.20)
Requirement already satisfied: MarkupSafe>=2.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jinja2->notebook->jupyter->pyvitae) (2.0.1)
Requirement already satisfied: python-igraph>=0.9.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from leidenalg->pyvitae) (0.9.1)
Requirement already satisfied: texttable>=1.6.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from python-igraph>=0.9.0->leidenalg->pyvitae) (1.6.3)
Requirement already satisfied: pillow>=6.2.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from matplotlib->pyvitae) (8.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from matplotlib->pyvitae) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from matplotlib->pyvitae) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from matplotlib->pyvitae) (0.10.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.5.3)
Requirement already satisfied: entrypoints>=0.2.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.3)
Requirement already satisfied: jupyterlab-pygments in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.1.2)
Requirement already satisfied: bleach in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (3.3.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (1.4.3)
Requirement already satisfied: testpath in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.5.0)
Requirement already satisfied: defusedxml in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.8.4)
Requirement already satisfied: async-generator in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter->pyvitae) (1.10)
Requirement already satisfied: nest-asyncio in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter->pyvitae) (1.5.1)
Requirement already satisfied: webencodings in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from bleach->nbconvert->jupyter->pyvitae) (0.5.1)
Requirement already satisfied: packaging in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from bleach->nbconvert->jupyter->pyvitae) (20.9)
Requirement already satisfied: pytz>=2017.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pandas->pyvitae) (2021.1)
Requirement already satisfied: qtpy in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from qtconsole->jupyter->pyvitae) (1.9.0)
Requirement already satisfied: patsy>=0.5 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from statsmodels->pyvitae) (0.5.1)

```

```
import VITAE
print(VITAE.__version__)

1.1.4
```
Thanks.

Best regards.

**Comment by jaydu1** [comment]
Hi,

Could you provide all the output information after `pip install --upgrade pyvitae`? Cause I didn't see the information saying that the package is installed successfully.

As shown in the following notebook:
https://colab.research.google.com/drive/157macYaSIUALft6rfvD1rzzsi1XJH1Vl?usp=sharing
If you install or upgrade the package successfully, you will see information like 
`Successfully installed ... pyvitae-1.1.6 ...`
at the end.

Best.

**Comment by rmathieu25** [comment]
Hello,

It is all that I get by upgrading.

I tried by setting a new conda environment from scratch it is still not working:

```
!pip install pyvitae 
Collecting pyvitae
  Using cached pyvitae-1.1.6-py3-none-any.whl (35 kB)
Collecting jupyter
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting pyvitae
  Using cached pyvitae-1.1.5-py3-none-any.whl (35 kB)
  Using cached pyvitae-1.1.4-py3-none-any.whl (35 kB)
Collecting seaborn
  Using cached seaborn-0.11.1-py3-none-any.whl (285 kB)
Collecting matplotlib
  Using cached matplotlib-3.4.2-cp39-cp39-manylinux1_x86_64.whl (10.3 MB)
Collecting umap-learn>=0.5.0
  Using cached umap_learn-0.5.1-py3-none-any.whl
Collecting pandas
  Using cached pandas-1.2.4-cp39-cp39-manylinux1_x86_64.whl (9.7 MB)
Collecting tensorflow-probability>=0.11.0
  Using cached tensorflow_probability-0.12.2-py2.py3-none-any.whl (4.8 MB)
Collecting scikit-learn
  Using cached scikit_learn-0.24.2-cp39-cp39-manylinux2010_x86_64.whl (23.8 MB)
Collecting statsmodels
  Using cached statsmodels-0.12.2-cp39-cp39-manylinux1_x86_64.whl (9.4 MB)
Collecting leidenalg
  Using cached leidenalg-0.8.4-cp39-cp39-manylinux2010_x86_64.whl (1.4 MB)
Collecting networkx
  Using cached networkx-2.5.1-py3-none-any.whl (1.6 MB)
Collecting scikit-misc
  Using cached scikit_misc-0.1.4-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (8.8 MB)
Collecting numba
  Using cached numba-0.53.1-cp39-cp39-manylinux2014_x86_64.whl (3.4 MB)
Collecting tensorflow>=2.3.0
  Using cached tensorflow-2.5.0-cp39-cp39-manylinux2010_x86_64.whl (454.4 MB)
Collecting six~=1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting numpy~=1.19.2
  Using cached numpy-1.19.5-cp39-cp39-manylinux2010_x86_64.whl (14.9 MB)
Collecting grpcio~=1.34.0
  Using cached grpcio-1.34.1-cp39-cp39-manylinux2014_x86_64.whl (4.0 MB)
Collecting wrapt~=1.12.1
  Using cached wrapt-1.12.1-cp39-cp39-linux_x86_64.whl
Collecting tensorboard~=2.5
  Using cached tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
Collecting h5py~=3.1.0
  Using cached h5py-3.1.0-cp39-cp39-manylinux1_x86_64.whl (4.4 MB)
Collecting typing-extensions~=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0
  Using cached tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
Collecting keras-nightly~=2.5.0.dev
  Using cached keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
Collecting keras-preprocessing~=1.1.2
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting gast==0.4.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.17.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: wheel~=0.35 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow>=2.3.0->pyvitae) (0.36.2)
Collecting termcolor~=1.1.0
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting absl-py~=0.10
  Using cached absl_py-0.12.0-py3-none-any.whl (129 kB)
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Requirement already satisfied: setuptools>=41.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (49.6.0.post20210108)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.30.1-py2.py3-none-any.whl (146 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.4-py3-none-any.whl (97 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow>=2.3.0->pyvitae) (2020.12.5)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Requirement already satisfied: decorator in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from tensorflow-probability>=0.11.0->pyvitae) (5.0.9)
Collecting cloudpickle>=1.3
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting dm-tree
  Using cached dm_tree-0.1.6-cp39-cp39-manylinux_2_24_x86_64.whl (94 kB)
Collecting scipy>=1.0
  Using cached scipy-1.6.3-cp39-cp39-manylinux1_x86_64.whl (27.3 MB)
Collecting pynndescent>=0.5
  Using cached pynndescent-0.5.2-py3-none-any.whl
Collecting llvmlite<0.37,>=0.36.0rc1
  Using cached llvmlite-0.36.0-cp39-cp39-manylinux2010_x86_64.whl (25.3 MB)
Collecting joblib>=0.11
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting ipywidgets
  Using cached ipywidgets-7.6.3-py2.py3-none-any.whl (121 kB)
Requirement already satisfied: notebook in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (6.4.0)
Requirement already satisfied: nbconvert in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (6.0.7)
Collecting qtconsole
  Using cached qtconsole-5.1.0-py3-none-any.whl (119 kB)
Requirement already satisfied: ipykernel in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter->pyvitae) (5.5.5)
Collecting jupyter-console
  Using cached jupyter_console-6.4.0-py3-none-any.whl (22 kB)
Requirement already satisfied: tornado>=4.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (6.1)
Requirement already satisfied: jupyter-client in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (6.1.12)
Requirement already satisfied: traitlets>=4.1.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (5.0.5)
Requirement already satisfied: ipython>=5.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipykernel->jupyter->pyvitae) (7.23.1)
Requirement already satisfied: pickleshare in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (3.0.18)
Requirement already satisfied: pexpect>4.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (4.8.0)
Requirement already satisfied: pygments in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (2.9.0)
Requirement already satisfied: jedi>=0.16 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.18.0)
Requirement already satisfied: matplotlib-inline in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.1.2)
Requirement already satisfied: backcall in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jedi>=0.16->ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.8.2)
Requirement already satisfied: ptyprocess>=0.5 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from pexpect>4.3->ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.7.0)
Requirement already satisfied: wcwidth in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->jupyter->pyvitae) (0.2.5)
Requirement already satisfied: ipython-genutils in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from traitlets>=4.1.0->ipykernel->jupyter->pyvitae) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from ipywidgets->jupyter->pyvitae) (5.1.3)
Collecting jupyterlab-widgets>=1.0.0
  Using cached jupyterlab_widgets-1.0.0-py3-none-any.whl (243 kB)
Collecting widgetsnbextension~=3.5.0
  Using cached widgetsnbextension-3.5.1-py2.py3-none-any.whl (2.2 MB)
Requirement already satisfied: jupyter-core in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (4.7.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (3.2.0)
Requirement already satisfied: attrs>=17.4.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter->pyvitae) (0.17.3)
Requirement already satisfied: Send2Trash>=1.5.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (1.5.0)
Requirement already satisfied: jinja2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (3.0.1)
Requirement already satisfied: terminado>=0.8.3 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (0.10.0)
Requirement already satisfied: pyzmq>=17 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (22.1.0)
Requirement already satisfied: prometheus-client in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (0.10.1)
Requirement already satisfied: argon2-cffi in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from notebook->jupyter->pyvitae) (20.1.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jupyter-client->ipykernel->jupyter->pyvitae) (2.8.1)
Requirement already satisfied: cffi>=1.0.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from argon2-cffi->notebook->jupyter->pyvitae) (1.14.5)
Requirement already satisfied: pycparser in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter->pyvitae) (2.20)
Requirement already satisfied: MarkupSafe>=2.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from jinja2->notebook->jupyter->pyvitae) (2.0.1)
Collecting python-igraph>=0.9.0
  Using cached python_igraph-0.9.1-cp39-cp39-manylinux2010_x86_64.whl (3.2 MB)
Collecting texttable>=1.6.2
  Using cached texttable-1.6.3-py2.py3-none-any.whl (10 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: pyparsing>=2.2.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from matplotlib->pyvitae) (2.4.7)
Collecting pillow>=6.2.0
  Using cached Pillow-8.2.0-cp39-cp39-manylinux1_x86_64.whl (3.0 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp39-cp39-manylinux1_x86_64.whl (1.2 MB)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.5.3)
Requirement already satisfied: mistune<2,>=0.8.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (1.4.2)
Requirement already satisfied: defusedxml in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.7.1)
Requirement already satisfied: testpath in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.5.0)
Requirement already satisfied: entrypoints>=0.2.2 in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.3)
Requirement already satisfied: bleach in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (3.3.0)
Requirement already satisfied: jupyterlab-pygments in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbconvert->jupyter->pyvitae) (0.1.2)
Requirement already satisfied: async-generator in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter->pyvitae) (1.10)
Requirement already satisfied: nest-asyncio in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter->pyvitae) (1.5.1)
Requirement already satisfied: packaging in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from bleach->nbconvert->jupyter->pyvitae) (20.9)
Requirement already satisfied: webencodings in /home/remi/anaconda3/envs/VITAE/lib/python3.9/site-packages (from bleach->nbconvert->jupyter->pyvitae) (0.5.1)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting qtpy
  Using cached QtPy-1.9.0-py2.py3-none-any.whl (54 kB)
Collecting patsy>=0.5
  Using cached patsy-0.5.1-py2.py3-none-any.whl (231 kB)
Installing collected packages: six, decorator, urllib3, pyasn1, idna, chardet, rsa, requests, pyasn1-modules, oauthlib, numpy, cachetools, threadpoolctl, scipy, requests-oauthlib, llvmlite, joblib, google-auth, widgetsnbextension, werkzeug, texttable, tensorboard-plugin-wit, tensorboard-data-server, scikit-learn, qtpy, pytz, protobuf, pillow, numba, markdown, kiwisolver, jupyterlab-widgets, grpcio, google-auth-oauthlib, cycler, absl-py, wrapt, typing-extensions, termcolor, tensorflow-estimator, tensorboard, qtconsole, python-igraph, pynndescent, patsy, pandas, opt-einsum, matplotlib, keras-preprocessing, keras-nightly, jupyter-console, ipywidgets, h5py, google-pasta, gast, flatbuffers, dm-tree, cloudpickle, astunparse, umap-learn, tensorflow-probability, tensorflow, statsmodels, seaborn, scikit-misc, networkx, leidenalg, jupyter, pyvitae
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: decorator
    Found existing installation: decorator 5.0.9
    Uninstalling decorator-5.0.9:
      Successfully uninstalled decorator-5.0.9
Successfully installed absl-py-0.12.0 astunparse-1.6.3 cachetools-4.2.2 chardet-4.0.0 cloudpickle-1.6.0 cycler-0.10.0 decorator-4.4.2 dm-tree-0.1.6 flatbuffers-1.12 gast-0.4.0 google-auth-1.30.1 google-auth-oauthlib-0.4.4 google-pasta-0.2.0 grpcio-1.34.1 h5py-3.1.0 idna-2.10 ipywidgets-7.6.3 joblib-1.0.1 jupyter-1.0.0 jupyter-console-6.4.0 jupyterlab-widgets-1.0.0 keras-nightly-2.5.0.dev2021032900 keras-preprocessing-1.1.2 kiwisolver-1.3.1 leidenalg-0.8.4 llvmlite-0.36.0 markdown-3.3.4 matplotlib-3.4.2 networkx-2.5.1 numba-0.53.1 numpy-1.19.5 oauthlib-3.1.0 opt-einsum-3.3.0 pandas-1.2.4 patsy-0.5.1 pillow-8.2.0 protobuf-3.17.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pynndescent-0.5.2 python-igraph-0.9.1 pytz-2021.1 pyvitae-1.1.4 qtconsole-5.1.0 qtpy-1.9.0 requests-2.25.1 requests-oauthlib-1.3.0 rsa-4.7.2 scikit-learn-0.24.2 scikit-misc-0.1.4 scipy-1.6.3 seaborn-0.11.1 six-1.15.0 statsmodels-0.12.2 tensorboard-2.5.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.5.0 tensorflow-estimator-2.5.0 tensorflow-probability-0.12.2 termcolor-1.1.0 texttable-1.6.3 threadpoolctl-2.1.0 typing-extensions-3.7.4.3 umap-learn-0.5.1 urllib3-1.26.5 werkzeug-2.0.1 widgetsnbextension-3.5.1 wrapt-1.12.1

```
```
import VITAE
print(VITAE.__version__)

1.1.4

```

However, in Google colab it is working I have the v1.1.6

Thanks.

Best regards.

**Comment by jaydu1** [comment]
I think this is not the problem with the package itself. Maybe the `pip` you use is not the one in the `conda` environment; in that case, the things may be much complicated. Maybe you can try:
```
pip uninstall pyvitae
```
and 
```
pip install pyvitae==1.1.6
```
I hope this will help.

**Comment by rmathieu25** [comment]
Hello,

By recreating my conda env from scratch and dealing with some packages, I was able to install the v1.1.6 with:

```
pip install pyvitae==1.1.6

```

Thank you again.

Best regards
